# Dataset Link:  http://archive.ics.uci.edu/ml/datasets/Iris

# Loading Data

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("iris.data")
df.columns = ["sepal length", "sepal width", "petal length", "petal width", "class"]
df

sepal length  sepal width  petal length  petal width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

# Preprocessing

In [ ]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

LE = LabelEncoder()
MMS = MinMaxScaler()

X = MMS.fit_transform(df.iloc[:, :-1])
y = LE.fit_transform(df.iloc[:, -1])

# Model Building

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(X_train, y_train)

y_pred = LR.predict(X_test)
y_pred

array([1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

# Comparing actual & predicted values

In [ ]:
pd.DataFrame([[y_test[i], y_pred[i], True if y_test[i] == y_pred[i] else False] for i in range(len(X_test))], columns = ['Actual', 'Prediction', 'T/F'])

Actual  Prediction    T/F
0        1           1   True
1        0           0   True
2        2           2   True
3        1           1   True
4        1           2  False
5        0           0   True
6        1           1   True
7        2           2   True
8        1           1   True
9        1           1   True
10       2           2   True
11       0           0   True
12       0           0   True
13       0           0   True
14       0           0   True
15       1           1   True
16       2           2   True
17       1           2  False
18       1           2  False
19       2           2   True
20       0           0   True
21       2           2   True
22       0           0   True
23       2           2   True
24       2           2   True
25       2           2   True
26       2           2   True
27       2           2   True
28       0           0   True
29       0           0   True

# Metrics

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
ps = precision_score(y_test, y_pred, average = 'weighted')
rs = recall_score(y_test, y_pred, average = 'weighted')
f1 = f1_score(y_test, y_pred, average = 'weighted')

print(f'Confusion Matrix: \n{cm}')
print(f'Accuracy Score: {acc}')
print(f'Precision Score: {ps}')
print(f'Recall Score: {rs}')
print(f'F1 Score: {f1}')

Confusion Matrix: 
[[10  0  0]
 [ 0  6  3]
 [ 0  0 11]]
Accuracy Score: 0.9
Precision Score: 0.9214285714285714
Recall Score: 0.9
F1 Score: 0.896
